// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WatchListScreening.Infrastructure.Data;

#nullable disable

namespace WatchListScreening.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816163345_Phase2Entities")]
    partial class Phase2Entities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WatchListScreening.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_AuditLogs_Action");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_EntityType_EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.HarvestedEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalData")
                        .HasColumnType("text");

                    b.Property<string>("Addresses")
                        .HasColumnType("text");

                    b.Property<string>("Aliases")
                        .HasColumnType("text");

                    b.Property<int?>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("CleanedFirstName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("CleanedFullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CleanedLastName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DateOfBirth")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("EntityType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("ListSourceId")
                        .HasColumnType("integer");

                    b.Property<int>("ListSourceRunId")
                        .HasColumnType("integer");

                    b.Property<string>("NationalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Passports")
                        .HasColumnType("text");

                    b.Property<string>("Positions")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RawCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RawFirstName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("RawFullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RawLastName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("SanctionEntryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CleanedFullName")
                        .HasDatabaseName("IX_HarvestedEntries_CleanedFullName");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("IX_HarvestedEntries_ContentHash_UNIQUE");

                    b.HasIndex("IsProcessed")
                        .HasDatabaseName("IX_HarvestedEntries_IsProcessed");

                    b.HasIndex("ListSourceId")
                        .HasDatabaseName("IX_HarvestedEntries_ListSourceId");

                    b.HasIndex("ListSourceRunId");

                    b.HasIndex("SanctionEntryId");

                    b.ToTable("HarvestedEntries", (string)null);
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.ListSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("HasScraperImpl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastHarvestAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<string>("ScraperClassName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ScraperConfig")
                        .HasColumnType("text");

                    b.Property<int>("ScraperType")
                        .HasColumnType("integer");

                    b.Property<int>("TimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(120);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_ListSources_Category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ListSources_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_ListSources_Name");

                    b.ToTable("ListSources", (string)null);
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.ListSourceRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ListSourceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalNew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalScraped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalSkipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ListSourceId")
                        .HasDatabaseName("IX_ListSourceRuns_ListSourceId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ListSourceRuns_Status");

                    b.ToTable("ListSourceRuns", (string)null);
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.SanctionEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("Aliases")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("ListSourceId")
                        .HasColumnType("integer");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Country")
                        .HasDatabaseName("IX_SanctionEntries_Country");

                    b.HasIndex("FullName")
                        .HasDatabaseName("IX_SanctionEntries_FullName");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_SanctionEntries_IsActive");

                    b.HasIndex("ListSourceId")
                        .HasDatabaseName("IX_SanctionEntries_ListSourceId");

                    b.ToTable("SanctionEntries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "United States",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1975, 3, 15),
                            EntityType = 1,
                            FullName = "John Alexander Smith",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Syria",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1980, 7, 22),
                            EntityType = 1,
                            FullName = "Ali Hassan Mohammed",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Russia",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityType = 2,
                            FullName = "Petrolex Trading Corp",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Turkey",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1968, 11, 3),
                            EntityType = 1,
                            FullName = "Mehmet Yılmaz",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Iran",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityType = 2,
                            FullName = "Golden Bridge Holdings Ltd",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Iraq",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1992, 4, 18),
                            EntityType = 1,
                            FullName = "Fatima Al-Rashid",
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Germany",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityType = 2,
                            FullName = "Nord Stream Finance GmbH",
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Venezuela",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1971, 9, 30),
                            EntityType = 1,
                            FullName = "Carlos Rodriguez Vega",
                            IsActive = true
                        },
                        new
                        {
                            Id = 9,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "North Korea",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityType = 2,
                            FullName = "Bright Star Logistics",
                            IsActive = true
                        },
                        new
                        {
                            Id = 10,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Turkey",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1985, 6, 14),
                            EntityType = 1,
                            FullName = "Ayşe Demir",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.ScreeningRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsBulk")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SearchType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalMatches")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("RequestedBy")
                        .HasDatabaseName("IX_ScreeningRequests_RequestedBy");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ScreeningRequests_Status");

                    b.ToTable("ScreeningRequests", (string)null);
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.ScreeningResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("MatchScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("MatchedType")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<int>("SanctionEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("ScreeningRequestId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReviewStatus")
                        .HasDatabaseName("IX_ScreeningResults_ReviewStatus");

                    b.HasIndex("RiskLevel")
                        .HasDatabaseName("IX_ScreeningResults_RiskLevel");

                    b.HasIndex("SanctionEntryId")
                        .HasDatabaseName("IX_ScreeningResults_SanctionEntryId");

                    b.HasIndex("ScreeningRequestId")
                        .HasDatabaseName("IX_ScreeningResults_ScreeningRequestId");

                    b.ToTable("ScreeningResults", (string)null);
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.HarvestedEntry", b =>
                {
                    b.HasOne("WatchListScreening.Domain.Entities.ListSource", "ListSource")
                        .WithMany("HarvestedEntries")
                        .HasForeignKey("ListSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchListScreening.Domain.Entities.ListSourceRun", "ListSourceRun")
                        .WithMany("HarvestedEntries")
                        .HasForeignKey("ListSourceRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchListScreening.Domain.Entities.SanctionEntry", "SanctionEntry")
                        .WithMany("HarvestedEntries")
                        .HasForeignKey("SanctionEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ListSource");

                    b.Navigation("ListSourceRun");

                    b.Navigation("SanctionEntry");
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.ListSourceRun", b =>
                {
                    b.HasOne("WatchListScreening.Domain.Entities.ListSource", "ListSource")
                        .WithMany("Runs")
                        .HasForeignKey("ListSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListSource");
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.SanctionEntry", b =>
                {
                    b.HasOne("WatchListScreening.Domain.Entities.ListSource", "ListSourceRef")
                        .WithMany("SanctionEntries")
                        .HasForeignKey("ListSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ListSourceRef");
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.ScreeningResult", b =>
                {
                    b.HasOne("WatchListScreening.Domain.Entities.SanctionEntry", "SanctionEntry")
                        .WithMany("ScreeningResults")
                        .HasForeignKey("SanctionEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WatchListScreening.Domain.Entities.ScreeningRequest", "ScreeningRequest")
                        .WithMany("Results")
                        .HasForeignKey("ScreeningRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanctionEntry");

                    b.Navigation("ScreeningRequest");
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.ListSource", b =>
                {
                    b.Navigation("HarvestedEntries");

                    b.Navigation("Runs");

                    b.Navigation("SanctionEntries");
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.ListSourceRun", b =>
                {
                    b.Navigation("HarvestedEntries");
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.SanctionEntry", b =>
                {
                    b.Navigation("HarvestedEntries");

                    b.Navigation("ScreeningResults");
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.ScreeningRequest", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
