// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WatchListScreening.Infrastructure.Data;

#nullable disable

namespace WatchListScreening.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WatchListScreening.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_AuditLogs_Action");

                    b.HasIndex("PerformedAt")
                        .HasDatabaseName("IX_AuditLogs_PerformedAt");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_EntityType_EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.SanctionEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("Aliases")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ListSource")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ListSourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Country")
                        .HasDatabaseName("IX_SanctionEntries_Country");

                    b.HasIndex("FullName")
                        .HasDatabaseName("IX_SanctionEntries_FullName");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_SanctionEntries_IsActive");

                    b.HasIndex("ListSource")
                        .HasDatabaseName("IX_SanctionEntries_ListSource");

                    b.ToTable("SanctionEntries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "United States",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1975, 3, 15),
                            EntityType = 1,
                            FullName = "John Alexander Smith",
                            IsActive = true,
                            ListSource = "OFAC"
                        },
                        new
                        {
                            Id = 2,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Syria",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1980, 7, 22),
                            EntityType = 1,
                            FullName = "Ali Hassan Mohammed",
                            IsActive = true,
                            ListSource = "UN"
                        },
                        new
                        {
                            Id = 3,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Russia",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityType = 2,
                            FullName = "Petrolex Trading Corp",
                            IsActive = true,
                            ListSource = "EU"
                        },
                        new
                        {
                            Id = 4,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Turkey",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1968, 11, 3),
                            EntityType = 1,
                            FullName = "Mehmet Yılmaz",
                            IsActive = true,
                            ListSource = "MASAK"
                        },
                        new
                        {
                            Id = 5,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Iran",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityType = 2,
                            FullName = "Golden Bridge Holdings Ltd",
                            IsActive = true,
                            ListSource = "OFAC"
                        },
                        new
                        {
                            Id = 6,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Iraq",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1992, 4, 18),
                            EntityType = 1,
                            FullName = "Fatima Al-Rashid",
                            IsActive = true,
                            ListSource = "UN"
                        },
                        new
                        {
                            Id = 7,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Germany",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityType = 2,
                            FullName = "Nord Stream Finance GmbH",
                            IsActive = true,
                            ListSource = "EU"
                        },
                        new
                        {
                            Id = 8,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Venezuela",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1971, 9, 30),
                            EntityType = 1,
                            FullName = "Carlos Rodriguez Vega",
                            IsActive = true,
                            ListSource = "OFAC"
                        },
                        new
                        {
                            Id = 9,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "North Korea",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityType = 2,
                            FullName = "Bright Star Logistics",
                            IsActive = true,
                            ListSource = "UN"
                        },
                        new
                        {
                            Id = 10,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Turkey",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1985, 6, 14),
                            EntityType = 1,
                            FullName = "Ayşe Demir",
                            IsActive = true,
                            ListSource = "MASAK"
                        });
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.ScreeningRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBulk")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SearchType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalMatches")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("IX_ScreeningRequests_RequestedAt");

                    b.HasIndex("RequestedBy")
                        .HasDatabaseName("IX_ScreeningRequests_RequestedBy");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ScreeningRequests_Status");

                    b.ToTable("ScreeningRequests", (string)null);
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.ScreeningResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MatchScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("MatchedType")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<int>("SanctionEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("ScreeningRequestId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReviewStatus")
                        .HasDatabaseName("IX_ScreeningResults_ReviewStatus");

                    b.HasIndex("RiskLevel")
                        .HasDatabaseName("IX_ScreeningResults_RiskLevel");

                    b.HasIndex("SanctionEntryId")
                        .HasDatabaseName("IX_ScreeningResults_SanctionEntryId");

                    b.HasIndex("ScreeningRequestId")
                        .HasDatabaseName("IX_ScreeningResults_ScreeningRequestId");

                    b.ToTable("ScreeningResults", (string)null);
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.ScreeningResult", b =>
                {
                    b.HasOne("WatchListScreening.Domain.Entities.SanctionEntry", "SanctionEntry")
                        .WithMany("ScreeningResults")
                        .HasForeignKey("SanctionEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WatchListScreening.Domain.Entities.ScreeningRequest", "ScreeningRequest")
                        .WithMany("Results")
                        .HasForeignKey("ScreeningRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanctionEntry");

                    b.Navigation("ScreeningRequest");
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.SanctionEntry", b =>
                {
                    b.Navigation("ScreeningResults");
                });

            modelBuilder.Entity("WatchListScreening.Domain.Entities.ScreeningRequest", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
